-- MySQL Script generated by MySQL Workbench
-- Thu May 23 00:10:40 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bx2gb5k16nirhsbngltz
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bx2gb5k16nirhsbngltz
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bx2gb5k16nirhsbngltz` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema bauwm9qrxcngjlchzbxp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bauwm9qrxcngjlchzbxp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bauwm9qrxcngjlchzbxp` DEFAULT CHARACTER SET utf8 ;
USE `bx2gb5k16nirhsbngltz` ;

-- -----------------------------------------------------
-- Table `bx2gb5k16nirhsbngltz`.`failed_jobs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bx2gb5k16nirhsbngltz`.`failed_jobs` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(255) NOT NULL,
  `connection` TEXT NOT NULL,
  `queue` TEXT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `exception` LONGTEXT NOT NULL,
  `failed_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `failed_jobs_uuid_unique` (`uuid` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `bx2gb5k16nirhsbngltz`.`migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bx2gb5k16nirhsbngltz`.`migrations` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `migration` VARCHAR(255) NOT NULL,
  `batch` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `bx2gb5k16nirhsbngltz`.`password_reset_tokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bx2gb5k16nirhsbngltz`.`password_reset_tokens` (
  `email` VARCHAR(255) NOT NULL,
  `token` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `bx2gb5k16nirhsbngltz`.`personal_access_tokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bx2gb5k16nirhsbngltz`.`personal_access_tokens` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `tokenable_type` VARCHAR(255) NOT NULL,
  `tokenable_id` BIGINT(20) UNSIGNED NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `token` VARCHAR(64) NOT NULL,
  `abilities` TEXT NULL DEFAULT NULL,
  `last_used_at` TIMESTAMP NULL DEFAULT NULL,
  `expires_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `personal_access_tokens_token_unique` (`token` ASC) VISIBLE,
  INDEX `personal_access_tokens_tokenable_type_tokenable_id_index` (`tokenable_type` ASC, `tokenable_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `bx2gb5k16nirhsbngltz`.`pulse_aggregates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bx2gb5k16nirhsbngltz`.`pulse_aggregates` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `bucket` INT(10) UNSIGNED NOT NULL,
  `period` MEDIUMINT(8) UNSIGNED NOT NULL,
  `type` VARCHAR(255) NOT NULL,
  `key` MEDIUMTEXT NOT NULL,
  `key_hash` BINARY(16) GENERATED ALWAYS AS (unhex(md5(`key`))) VIRTUAL,
  `aggregate` VARCHAR(255) NOT NULL,
  `value` DECIMAL(20,2) NOT NULL,
  `count` INT(10) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `pulse_aggregates_bucket_period_type_aggregate_key_hash_unique` (`bucket` ASC, `period` ASC, `type` ASC, `aggregate` ASC, `key_hash` ASC) VISIBLE,
  INDEX `pulse_aggregates_period_bucket_index` (`period` ASC, `bucket` ASC) VISIBLE,
  INDEX `pulse_aggregates_type_index` (`type` ASC) VISIBLE,
  INDEX `pulse_aggregates_period_type_aggregate_bucket_index` (`period` ASC, `type` ASC, `aggregate` ASC, `bucket` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 1561
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `bx2gb5k16nirhsbngltz`.`pulse_entries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bx2gb5k16nirhsbngltz`.`pulse_entries` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `timestamp` INT(10) UNSIGNED NOT NULL,
  `type` VARCHAR(255) NOT NULL,
  `key` MEDIUMTEXT NOT NULL,
  `key_hash` BINARY(16) GENERATED ALWAYS AS (unhex(md5(`key`))) VIRTUAL,
  `value` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `pulse_entries_timestamp_index` (`timestamp` ASC) VISIBLE,
  INDEX `pulse_entries_type_index` (`type` ASC) VISIBLE,
  INDEX `pulse_entries_key_hash_index` (`key_hash` ASC) VISIBLE,
  INDEX `pulse_entries_timestamp_type_key_hash_value_index` (`timestamp` ASC, `type` ASC, `key_hash` ASC, `value` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 88
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `bx2gb5k16nirhsbngltz`.`pulse_values`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bx2gb5k16nirhsbngltz`.`pulse_values` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `timestamp` INT(10) UNSIGNED NOT NULL,
  `type` VARCHAR(255) NOT NULL,
  `key` MEDIUMTEXT NOT NULL,
  `key_hash` BINARY(16) GENERATED ALWAYS AS (unhex(md5(`key`))) VIRTUAL,
  `value` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `pulse_values_type_key_hash_unique` (`type` ASC, `key_hash` ASC) VISIBLE,
  INDEX `pulse_values_timestamp_index` (`timestamp` ASC) VISIBLE,
  INDEX `pulse_values_type_index` (`type` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 135
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `bx2gb5k16nirhsbngltz`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bx2gb5k16nirhsbngltz`.`users` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `email_verified_at` TIMESTAMP NULL DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `remember_token` VARCHAR(100) NULL DEFAULT NULL,
  `status` INT(11) NOT NULL DEFAULT '1',
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `profile` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `users_email_unique` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `bx2gb5k16nirhsbngltz`.`careers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bx2gb5k16nirhsbngltz`.`careers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bx2gb5k16nirhsbngltz`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bx2gb5k16nirhsbngltz`.`students` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `mother_last_name` VARCHAR(45) NULL,
  `control_number` VARCHAR(45) NULL,
  `status` INT NULL,
  `profile_picture` LONGTEXT NULL,
  `phone` VARCHAR(10) NULL,
  `profile` VARCHAR(45) NULL,
  `semester` INT NULL,
  `gender` VARCHAR(45) NULL,
  `careers_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `control_number_UNIQUE` (`control_number` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC) VISIBLE,
  INDEX `fk_students_careers1_idx` (`careers_id` ASC) VISIBLE,
  CONSTRAINT `fk_students_careers1`
    FOREIGN KEY (`careers_id`)
    REFERENCES `bx2gb5k16nirhsbngltz`.`careers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bx2gb5k16nirhsbngltz`.`departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bx2gb5k16nirhsbngltz`.`departments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bx2gb5k16nirhsbngltz`.`teachers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bx2gb5k16nirhsbngltz`.`teachers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `mother_last_name` VARCHAR(45) NULL,
  `gender` VARCHAR(45) NULL,
  `abbreviated_title` VARCHAR(45) NULL,
  `curp` VARCHAR(45) NULL,
  `rfc` VARCHAR(45) NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `profile_picture` LONGTEXT NULL,
  `signature` LONGTEXT NULL,
  `profile` VARCHAR(45) NULL,
  `departments_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `rfc_UNIQUE` (`rfc` ASC) VISIBLE,
  UNIQUE INDEX `curp_UNIQUE` (`curp` ASC) VISIBLE,
  INDEX `fk_teachers_departments1_idx` (`departments_id` ASC) VISIBLE,
  CONSTRAINT `fk_teachers_departments1`
    FOREIGN KEY (`departments_id`)
    REFERENCES `bx2gb5k16nirhsbngltz`.`departments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bx2gb5k16nirhsbngltz`.`type_of_activities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bx2gb5k16nirhsbngltz`.`type_of_activities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bx2gb5k16nirhsbngltz`.`activities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bx2gb5k16nirhsbngltz`.`activities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `code` VARCHAR(45) NULL,
  `image` LONGTEXT NULL,
  `type_of_activities_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_activities_type_of_activities1_idx` (`type_of_activities_id` ASC) VISIBLE,
  CONSTRAINT `fk_activities_type_of_activities1`
    FOREIGN KEY (`type_of_activities_id`)
    REFERENCES `bx2gb5k16nirhsbngltz`.`type_of_activities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bx2gb5k16nirhsbngltz`.`type_of_groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bx2gb5k16nirhsbngltz`.`type_of_groups` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bx2gb5k16nirhsbngltz`.`periods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bx2gb5k16nirhsbngltz`.`periods` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `start_period` DATE NULL,
  `end_period` DATE NULL,
  `period` VARCHAR(45) NULL,
  `registration_start` DATE NULL,
  `registration_end` DATE NULL,
  `selectiv_start` DATE NULL,
  `selectiv_end` DATE NULL,
  `periodscol` VARCHAR(45) NULL,
  `status` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bx2gb5k16nirhsbngltz`.`groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bx2gb5k16nirhsbngltz`.`groups` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quota_limit` INT NULL,
  `location` LONGTEXT NULL,
  `periods_id` INT NOT NULL,
  `teachers_id` INT NOT NULL,
  `activities_id` INT NOT NULL,
  `type_of_groups_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_groups_periods1_idx` (`periods_id` ASC) VISIBLE,
  INDEX `fk_groups_teachers1_idx` (`teachers_id` ASC) VISIBLE,
  INDEX `fk_groups_activities1_idx` (`activities_id` ASC) VISIBLE,
  INDEX `fk_groups_type_of_groups1_idx` (`type_of_groups_id` ASC) VISIBLE,
  CONSTRAINT `fk_groups_periods1`
    FOREIGN KEY (`periods_id`)
    REFERENCES `bx2gb5k16nirhsbngltz`.`periods` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_groups_teachers1`
    FOREIGN KEY (`teachers_id`)
    REFERENCES `bx2gb5k16nirhsbngltz`.`teachers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_groups_activities1`
    FOREIGN KEY (`activities_id`)
    REFERENCES `bx2gb5k16nirhsbngltz`.`activities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_groups_type_of_groups1`
    FOREIGN KEY (`type_of_groups_id`)
    REFERENCES `bx2gb5k16nirhsbngltz`.`type_of_groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bx2gb5k16nirhsbngltz`.`schedules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bx2gb5k16nirhsbngltz`.`schedules` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `day` ENUM('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday') NULL,
  `start_time` VARCHAR(45) NULL,
  `end_time` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bx2gb5k16nirhsbngltz`.`group_schedules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bx2gb5k16nirhsbngltz`.`group_schedules` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `groups_id` INT NOT NULL,
  `schedules_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_group_schedules_groups1_idx` (`groups_id` ASC) VISIBLE,
  INDEX `fk_group_schedules_schedules1_idx` (`schedules_id` ASC) VISIBLE,
  CONSTRAINT `fk_group_schedules_groups1`
    FOREIGN KEY (`groups_id`)
    REFERENCES `bx2gb5k16nirhsbngltz`.`groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_group_schedules_schedules1`
    FOREIGN KEY (`schedules_id`)
    REFERENCES `bx2gb5k16nirhsbngltz`.`schedules` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bx2gb5k16nirhsbngltz`.`surveys`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bx2gb5k16nirhsbngltz`.`surveys` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bx2gb5k16nirhsbngltz`.`questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bx2gb5k16nirhsbngltz`.`questions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `question` VARCHAR(45) NULL,
  `surveys_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_questions_surveys1_idx` (`surveys_id` ASC) VISIBLE,
  CONSTRAINT `fk_questions_surveys1`
    FOREIGN KEY (`surveys_id`)
    REFERENCES `bx2gb5k16nirhsbngltz`.`surveys` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bx2gb5k16nirhsbngltz`.`options`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bx2gb5k16nirhsbngltz`.`options` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `answer` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bx2gb5k16nirhsbngltz`.`question_options`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bx2gb5k16nirhsbngltz`.`question_options` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `opcion` VARCHAR(45) NULL,
  `options_id` INT NOT NULL,
  `questions_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_question_options_options1_idx` (`options_id` ASC) VISIBLE,
  INDEX `fk_question_options_questions1_idx` (`questions_id` ASC) VISIBLE,
  CONSTRAINT `fk_question_options_options1`
    FOREIGN KEY (`options_id`)
    REFERENCES `bx2gb5k16nirhsbngltz`.`options` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_question_options_questions1`
    FOREIGN KEY (`questions_id`)
    REFERENCES `bx2gb5k16nirhsbngltz`.`questions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bx2gb5k16nirhsbngltz`.`responses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bx2gb5k16nirhsbngltz`.`responses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `options_id` INT NOT NULL,
  `questions_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_responses_options1_idx` (`options_id` ASC) VISIBLE,
  INDEX `fk_responses_questions1_idx` (`questions_id` ASC) VISIBLE,
  CONSTRAINT `fk_responses_options1`
    FOREIGN KEY (`options_id`)
    REFERENCES `bx2gb5k16nirhsbngltz`.`options` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_responses_questions1`
    FOREIGN KEY (`questions_id`)
    REFERENCES `bx2gb5k16nirhsbngltz`.`questions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bx2gb5k16nirhsbngltz`.`survey_responses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bx2gb5k16nirhsbngltz`.`survey_responses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `surveys_id` INT NOT NULL,
  `responses_id` INT NOT NULL,
  `teachers_id` INT NOT NULL,
  `students_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_survey_responses_surveys1_idx` (`surveys_id` ASC) VISIBLE,
  INDEX `fk_survey_responses_responses1_idx` (`responses_id` ASC) VISIBLE,
  INDEX `fk_survey_responses_teachers1_idx` (`teachers_id` ASC) VISIBLE,
  INDEX `fk_survey_responses_students1_idx` (`students_id` ASC) VISIBLE,
  CONSTRAINT `fk_survey_responses_surveys1`
    FOREIGN KEY (`surveys_id`)
    REFERENCES `bx2gb5k16nirhsbngltz`.`surveys` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_survey_responses_responses1`
    FOREIGN KEY (`responses_id`)
    REFERENCES `bx2gb5k16nirhsbngltz`.`responses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_survey_responses_teachers1`
    FOREIGN KEY (`teachers_id`)
    REFERENCES `bx2gb5k16nirhsbngltz`.`teachers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_survey_responses_students1`
    FOREIGN KEY (`students_id`)
    REFERENCES `bx2gb5k16nirhsbngltz`.`students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `bauwm9qrxcngjlchzbxp` ;

-- -----------------------------------------------------
-- Table `bauwm9qrxcngjlchzbxp`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bauwm9qrxcngjlchzbxp`.`customers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `apellido` VARCHAR(100) NOT NULL,
  `apellido2` VARCHAR(100) NOT NULL,
  `correo` VARCHAR(255) NOT NULL,
  `image` TEXT NULL DEFAULT NULL,
  `password` TEXT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `status` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL DEFAULT '1',
  `rutina` VARCHAR(50) NULL DEFAULT 'ninguna',
  `profileIsComplete` VARCHAR(5) NOT NULL DEFAULT 'no',
  `peso` INT NULL DEFAULT NULL,
  `altura` DOUBLE NULL DEFAULT NULL,
  `IMC` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bauwm9qrxcngjlchzbxp`.`rutinas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bauwm9qrxcngjlchzbxp`.`rutinas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `imagen` VARCHAR(255) NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `max_puntaje` INT NULL DEFAULT NULL,
  `tipo` VARCHAR(60) NULL DEFAULT NULL,
  `min_puntaje` INT NULL DEFAULT NULL,
  `estado` VARCHAR(30) NULL DEFAULT 'publica',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bauwm9qrxcngjlchzbxp`.`ejercicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bauwm9qrxcngjlchzbxp`.`ejercicios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rutina_id` INT NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  `imagen` VARCHAR(255) NOT NULL,
  `status` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `tipo` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_rutinas_ejercicios` (`rutina_id` ASC) VISIBLE,
  CONSTRAINT `fk_rutinas_ejercicios`
    FOREIGN KEY (`rutina_id`)
    REFERENCES `bauwm9qrxcngjlchzbxp`.`rutinas` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bauwm9qrxcngjlchzbxp`.`equipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bauwm9qrxcngjlchzbxp`.`equipo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bauwm9qrxcngjlchzbxp`.`grupos_musculares`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bauwm9qrxcngjlchzbxp`.`grupos_musculares` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `imagen` LONGTEXT NOT NULL,
  `descripcion` TEXT CHARACTER SET 'utf8' NOT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bauwm9qrxcngjlchzbxp`.`equipo_grupos_musculares`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bauwm9qrxcngjlchzbxp`.`equipo_grupos_musculares` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `grupos_musculares_id` INT NOT NULL,
  `equipo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_equipo_grupod_musculares_equipo1_idx` (`equipo_id` ASC) VISIBLE,
  INDEX `fk_equipo_grupod_musculares_grupos_musculares1_idx` (`grupos_musculares_id` ASC) VISIBLE,
  CONSTRAINT `fk_equipo_grupod_musculares_equipo1`
    FOREIGN KEY (`equipo_id`)
    REFERENCES `bauwm9qrxcngjlchzbxp`.`equipo` (`id`),
  CONSTRAINT `fk_equipo_grupod_musculares_grupos_musculares1`
    FOREIGN KEY (`grupos_musculares_id`)
    REFERENCES `bauwm9qrxcngjlchzbxp`.`grupos_musculares` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bauwm9qrxcngjlchzbxp`.`videos_gm`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bauwm9qrxcngjlchzbxp`.`videos_gm` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` TEXT NOT NULL,
  `descripcion` TEXT NOT NULL,
  `miniatura` TEXT NOT NULL,
  `video_url` TEXT NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NOT NULL,
  `gm_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_gm_videos` (`gm_id` ASC) VISIBLE,
  CONSTRAINT `fk_gm_videos`
    FOREIGN KEY (`gm_id`)
    REFERENCES `bauwm9qrxcngjlchzbxp`.`grupos_musculares` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 114
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bauwm9qrxcngjlchzbxp`.`equipo_videos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bauwm9qrxcngjlchzbxp`.`equipo_videos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `equipo_id` INT NOT NULL,
  `videos_gm_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_equipo_videos_equipo1_idx` (`equipo_id` ASC) VISIBLE,
  INDEX `fk_equipo_videos_videos_gm1_idx` (`videos_gm_id` ASC) VISIBLE,
  CONSTRAINT `fk_equipo_videos_equipo1`
    FOREIGN KEY (`equipo_id`)
    REFERENCES `bauwm9qrxcngjlchzbxp`.`equipo` (`id`),
  CONSTRAINT `fk_equipo_videos_videos_gm1`
    FOREIGN KEY (`videos_gm_id`)
    REFERENCES `bauwm9qrxcngjlchzbxp`.`videos_gm` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bauwm9qrxcngjlchzbxp`.`failed_jobs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bauwm9qrxcngjlchzbxp`.`failed_jobs` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(255) NOT NULL,
  `connection` TEXT NOT NULL,
  `queue` TEXT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `exception` LONGTEXT NOT NULL,
  `failed_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `failed_jobs_uuid_unique` (`uuid` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `bauwm9qrxcngjlchzbxp`.`mecanicas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bauwm9qrxcngjlchzbxp`.`mecanicas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bauwm9qrxcngjlchzbxp`.`migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bauwm9qrxcngjlchzbxp`.`migrations` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `migration` VARCHAR(255) NOT NULL,
  `batch` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `bauwm9qrxcngjlchzbxp`.`password_resets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bauwm9qrxcngjlchzbxp`.`password_resets` (
  `email` VARCHAR(255) NOT NULL,
  `token` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  INDEX `password_resets_email_index` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `bauwm9qrxcngjlchzbxp`.`preguntas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bauwm9qrxcngjlchzbxp`.`preguntas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pregunta` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bauwm9qrxcngjlchzbxp`.`respuestas_opciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bauwm9qrxcngjlchzbxp`.`respuestas_opciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `opcion` VARCHAR(45) NULL DEFAULT NULL,
  `preguntas_id` INT NOT NULL,
  `valor` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_respuestas_opciones_preguntas1_idx` (`preguntas_id` ASC) VISIBLE,
  CONSTRAINT `fk_respuestas_opciones_preguntas1`
    FOREIGN KEY (`preguntas_id`)
    REFERENCES `bauwm9qrxcngjlchzbxp`.`preguntas` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bauwm9qrxcngjlchzbxp`.`respuestas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bauwm9qrxcngjlchzbxp`.`respuestas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `respuestas_opciones_id` INT NOT NULL,
  `preguntas_id` INT NOT NULL,
  `customers_id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_respuestas_respuestas_opciones1_idx` (`respuestas_opciones_id` ASC) VISIBLE,
  INDEX `fk_respuestas_preguntas1_idx` (`preguntas_id` ASC) VISIBLE,
  INDEX `fk_respuestas_customers1_idx` (`customers_id` ASC) VISIBLE,
  CONSTRAINT `fk_respuestas_customers1`
    FOREIGN KEY (`customers_id`)
    REFERENCES `bauwm9qrxcngjlchzbxp`.`customers` (`id`),
  CONSTRAINT `fk_respuestas_preguntas1`
    FOREIGN KEY (`preguntas_id`)
    REFERENCES `bauwm9qrxcngjlchzbxp`.`preguntas` (`id`),
  CONSTRAINT `fk_respuestas_respuestas_opciones1`
    FOREIGN KEY (`respuestas_opciones_id`)
    REFERENCES `bauwm9qrxcngjlchzbxp`.`respuestas_opciones` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 74
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bauwm9qrxcngjlchzbxp`.`rutinas_clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bauwm9qrxcngjlchzbxp`.`rutinas_clientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `customers_id` INT NOT NULL,
  `rutinas_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_rutinas_clientes_customers1_idx` (`customers_id` ASC) VISIBLE,
  INDEX `fk_rutinas_clientes_rutinas1_idx` (`rutinas_id` ASC) VISIBLE,
  CONSTRAINT `fk_rutinas_clientes_customers1`
    FOREIGN KEY (`customers_id`)
    REFERENCES `bauwm9qrxcngjlchzbxp`.`customers` (`id`),
  CONSTRAINT `fk_rutinas_clientes_rutinas1`
    FOREIGN KEY (`rutinas_id`)
    REFERENCES `bauwm9qrxcngjlchzbxp`.`rutinas` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bauwm9qrxcngjlchzbxp`.`rutinas_ejercicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bauwm9qrxcngjlchzbxp`.`rutinas_ejercicios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rutinas_id` INT NOT NULL,
  `videos_gm_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_rutinas_ejercicios_videos_gm1_idx` (`videos_gm_id` ASC) VISIBLE,
  INDEX `fk_rutinas_ejercicios_rutinas1_idx` (`rutinas_id` ASC) VISIBLE,
  CONSTRAINT `fk_rutinas_ejercicios_rutinas1`
    FOREIGN KEY (`rutinas_id`)
    REFERENCES `bauwm9qrxcngjlchzbxp`.`rutinas` (`id`),
  CONSTRAINT `fk_rutinas_ejercicios_videos_gm1`
    FOREIGN KEY (`videos_gm_id`)
    REFERENCES `bauwm9qrxcngjlchzbxp`.`videos_gm` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 42
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bauwm9qrxcngjlchzbxp`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bauwm9qrxcngjlchzbxp`.`tags` (
  `id` INT(10) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bauwm9qrxcngjlchzbxp`.`tags_grupos_musculares`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bauwm9qrxcngjlchzbxp`.`tags_grupos_musculares` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `grupos_musculares_id` INT NOT NULL,
  `tags_id` INT(10) UNSIGNED ZEROFILL NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tags_grupos_musculares_grupos_musculares1_idx` (`grupos_musculares_id` ASC) VISIBLE,
  INDEX `fk_tags_grupos_musculares_tags1_idx` (`tags_id` ASC) VISIBLE,
  CONSTRAINT `fk_tags_grupos_musculares_grupos_musculares1`
    FOREIGN KEY (`grupos_musculares_id`)
    REFERENCES `bauwm9qrxcngjlchzbxp`.`grupos_musculares` (`id`),
  CONSTRAINT `fk_tags_grupos_musculares_tags1`
    FOREIGN KEY (`tags_id`)
    REFERENCES `bauwm9qrxcngjlchzbxp`.`tags` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bauwm9qrxcngjlchzbxp`.`tags_videos_gm`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bauwm9qrxcngjlchzbxp`.`tags_videos_gm` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `videos_gm_id` INT NOT NULL,
  `tags_id` INT(10) UNSIGNED ZEROFILL NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tags_videos_gm_videos_gm1_idx` (`videos_gm_id` ASC) VISIBLE,
  INDEX `fk_tags_videos_gm_tags1_idx` (`tags_id` ASC) VISIBLE,
  CONSTRAINT `fk_tags_videos_gm_tags1`
    FOREIGN KEY (`tags_id`)
    REFERENCES `bauwm9qrxcngjlchzbxp`.`tags` (`id`),
  CONSTRAINT `fk_tags_videos_gm_videos_gm1`
    FOREIGN KEY (`videos_gm_id`)
    REFERENCES `bauwm9qrxcngjlchzbxp`.`videos_gm` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bauwm9qrxcngjlchzbxp`.`tipo_ejercicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bauwm9qrxcngjlchzbxp`.`tipo_ejercicio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bauwm9qrxcngjlchzbxp`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bauwm9qrxcngjlchzbxp`.`users` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `email_verified_at` TIMESTAMP NULL DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(255) NULL DEFAULT NULL,
  `location` VARCHAR(255) NULL DEFAULT NULL,
  `about` TEXT NULL DEFAULT NULL,
  `remember_token` VARCHAR(100) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `users_email_unique` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `bauwm9qrxcngjlchzbxp`.`videos_ejercicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bauwm9qrxcngjlchzbxp`.`videos_ejercicios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `videos_gm_id` INT NOT NULL,
  `ejercicios_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_videos_ejercicios_videos_gm1_idx` (`videos_gm_id` ASC) VISIBLE,
  INDEX `fk_videos_ejercicios_ejercicios1_idx` (`ejercicios_id` ASC) VISIBLE,
  CONSTRAINT `fk_videos_ejercicios_ejercicios1`
    FOREIGN KEY (`ejercicios_id`)
    REFERENCES `bauwm9qrxcngjlchzbxp`.`ejercicios` (`id`),
  CONSTRAINT `fk_videos_ejercicios_videos_gm1`
    FOREIGN KEY (`videos_gm_id`)
    REFERENCES `bauwm9qrxcngjlchzbxp`.`videos_gm` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bauwm9qrxcngjlchzbxp`.`videos_mecanicas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bauwm9qrxcngjlchzbxp`.`videos_mecanicas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mecanicas_id` INT NOT NULL,
  `videos_gm_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_videos_mecanicas_mecanicas1_idx` (`mecanicas_id` ASC) VISIBLE,
  INDEX `fk_videos_mecanicas_videos_gm1_idx` (`videos_gm_id` ASC) VISIBLE,
  CONSTRAINT `fk_videos_mecanicas_mecanicas1`
    FOREIGN KEY (`mecanicas_id`)
    REFERENCES `bauwm9qrxcngjlchzbxp`.`mecanicas` (`id`),
  CONSTRAINT `fk_videos_mecanicas_videos_gm1`
    FOREIGN KEY (`videos_gm_id`)
    REFERENCES `bauwm9qrxcngjlchzbxp`.`videos_gm` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bauwm9qrxcngjlchzbxp`.`videos_tipo_ejercicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bauwm9qrxcngjlchzbxp`.`videos_tipo_ejercicio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo_ejercicio_id` INT NOT NULL,
  `videos_gm_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_videos_tipo_ejercicio_tipo_ejercicio1_idx` (`tipo_ejercicio_id` ASC) VISIBLE,
  INDEX `fk_videos_tipo_ejercicio_videos_gm1_idx` (`videos_gm_id` ASC) VISIBLE,
  CONSTRAINT `fk_videos_tipo_ejercicio_tipo_ejercicio1`
    FOREIGN KEY (`tipo_ejercicio_id`)
    REFERENCES `bauwm9qrxcngjlchzbxp`.`tipo_ejercicio` (`id`),
  CONSTRAINT `fk_videos_tipo_ejercicio_videos_gm1`
    FOREIGN KEY (`videos_gm_id`)
    REFERENCES `bauwm9qrxcngjlchzbxp`.`videos_gm` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
